spring.application.name=Buoi5
spring.security.oauth2.client.registration.google.client-id=20116229681-cj8mv2in68s3sbss9sl2cadnv34do3gl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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